# Generated by Django 6.0.4 on 2026-05-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0002_order_status_product_description_product_frame_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
