# Generated by Django 6.0.4 on 2026-05-05 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0003_remove_order_is_paid_remove_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
