# Generated by Django 6.0.4 on 2026-05-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0005_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
